### PR TITLE
Structural Changes

### PR DESCRIPTION
**Pull request by balasankarc**
Closes: #6 
#### Changes
- Use namespace package - `libindic`
- Change package name to `libindic-normalizer`
- Add python3 support
- Add Travis and Circle CI support
- Add Coveralls support
- Reduce complexity of methods - Standardize rules to not use double quotes

### CODE REVIEW

**Comment by copyninja** [comment]
CircleCI fails please check

**Comment by balasankarc** [comment]
@copyninja Eh? CircleCI passed. I can see the little tick above.

**Comment by copyninja** [comment]
That is Travis. Check https://circleci.com/gh/libindic/normalizer/2, probably issue is circle.yml

**Comment by balasankarc** [comment]
@copyninja That is just CircleCI being an idiot, it seems.
1. It built fine with my repo - https://circleci.com/gh/balasankarc/normalizer/2 without any problem
2. That check has alt text mentioning that tests passed in CircleCI (See attachment)
3. The build log says it can't find Python 3.5.0. I used the same CircleCI file I used for all the other repos we added to CircleCI.

Remember, we had travis showing these kind of symptoms.

screenshot from 2016-10-10 23-37-06

**Pull request merged**
